name: util_tracker
description: >- 
  A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/brookbnu/util_tracker

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0

  transmogrify:
    path: ../functions

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
